server:
  port: 8885
logging:
  file: hryweb.log
  level:
    com.haier.controller: debug
    com.haier.interceptor: debug
    com.haier.service: debug
    com.haier.service.impl: debug
spring:
  application:
    name: hryweb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.180.100:3306/hry?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 8
      initialSize: 0
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 300000
      minEvictableIdleTimeMillis: 3600000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/static/
    suffix: .html
mybatis:
  mapper-locations: com/haier/mapper/*.xml
  type-aliases-package: com.haier.po









