zdy:
  reportPath: /opt/app/hryAuto/testngReport/
  resourcePathPattern: /test-output/
  autoCodeDir: /opt/app/hryAuto/autoCode/
  debug: false
server:
  port: 8885
logging:
  file: /opt/logs/hryAuto/hryAuto.log
#  level:
#    com.haier.mapper.*: debug
spring:
  application:
    name: hryweb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.251.12.106:3306/hry_auto?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: hryauto
    password: hryauto
    druid:
#      name: myDatasource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      max-create-task-count: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,log4j
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: com/haier/mapper/*.xml
  type-aliases-package: com.haier.po









