zdy:
  reportPath: /opt/app_java1.8/testngReport/
  resourcePathPattern: /test-output/
  autoCodeDir: /opt/app_java1.8/autoCode/
  debug: false
server:
  port: 8885
logging:
  file: /opt/logs/hryAuto/hryAuto.log
  level:
    com.haier.mapper.*: debug
spring:
  application:
    name: hryweb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.251.12.106:3306/hry_auto?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: hryauto
    password: hryauto
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 8
      initialSize: 0
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 300000
      minEvictableIdleTimeMillis: 3600000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: com/haier/mapper/*.xml
  type-aliases-package: com.haier.po









