spring:
  profiles:
    active: dev
unionlogin:
  loginInfoDetails:
    -
      #测试1
      envId: 1
      url: http://10.251.104.1:8211/hry-uni-login/login
      username: supper2
      password: kjt123
    -
      #测试2
      envId: 2
      url: http://10.252.104.1:8211/hry-uni-login/login
      username: supper2
      password: kjt123
    -
      #准生产
      envId: 5
      url: http://10.255.104.1:8211/hry-uni-login/login
      username: supper2
      password: kjt123